version: '3.8'

networks:
  lan1:
    name: lan1
    ipam:
      driver: default
      config:
        - subnet: 10.3.1.0/24
  lan2:
    name: lan2
    ipam:
      driver: default
      config:
        - subnet: 10.3.2.0/24

volumes:
  pgdata:
    driver: local

services:
  nginx:
    image:          nginx
    hostname:       caliber_nginx
    container_name: caliber_nginx
    restart:        unless-stopped
    tty:            true
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - php
    ports:
      - 12231:80
    networks:
      lan1:
        ipv4_address: 10.3.1.2

  php:
    build:
      dockerfile: php/Dockerfile
      context:    ./
    hostname:       caliber_php
    container_name: caliber_php
    restart:        unless-stopped
    tty:            true
    working_dir:    /var/www
    depends_on:
      - db
      - redis
    volumes:
      - ./:/var/www
      - /tmp/cache:/tmp/cache
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      lan1:
        ipv4_address: 10.3.1.3
      lan2:
        ipv4_address: 10.3.2.2

  redis:
    image:          redis:latest
    hostname:       caliber_redis
    container_name: caliber_redis
    restart:        unless-stopped
    ports:
      - 12233:6379
    networks:
      lan1:
        ipv4_address: 10.3.1.4

  db:
    image:          postgres:latest
    hostname:       caliber_db
    container_name: caliber_db
    restart:        unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 12232:5432
    networks:
      lan2:
        ipv4_address: 10.3.2.3
